### ISSUE TITLE
[java, full] Add Maven and Gradle

### ISSUE THREAD

**Issue by UdoW** [theia-ide/theia-apps#152]
I started the docker image theiaide/theia-java:0.4.0.

If I open Theia in the browser I see the empty workspace.

Then I go to the terminal an checkout a git project.

After that I get following error messages in the console of my docker container:

 

2019-03-21T06:22:15.929755700Z root ERROR Error occurred while synchronizing the status of the repository. file:///home/project/screeneditor-creator GitError: error: option `porcelain' takes no value
2019-03-21T06:22:15.929855200Z usage: git status [<options>] [--] <pathspec>...
2019-03-21T06:22:15.929863300Z 
2019-03-21T06:22:15.929866600Z     -v, --verbose         be verbose
2019-03-21T06:22:15.929869600Z     -s, --short           show status concisely
2019-03-21T06:22:15.929872500Z     -b, --branch          show branch information
2019-03-21T06:22:15.929875400Z     --porcelain           machine-readable output
2019-03-21T06:22:15.929878300Z     --long                show status in long format (default)
2019-03-21T06:22:15.929881100Z     -z, --null            terminate entries with NUL
2019-03-21T06:22:15.929884100Z     -u, --untracked-files[=<mode>]
2019-03-21T06:22:15.929887100Z                           show untracked files, optional modes: all, normal, no. (Default: all)
2019-03-21T06:22:15.929890200Z     --ignored             show ignored files
2019-03-21T06:22:15.929895000Z     --ignore-submodules[=<when>]
2019-03-21T06:22:15.929900100Z                           ignore changes to submodules, optional when: all, dirty, untracked. (Default: all)
2019-03-21T06:22:15.929904900Z     --column[=<style>]    list untracked files in columns
2019-03-21T06:22:15.929909600Z 
2019-03-21T06:22:15.929913900Z 
2019-03-21T06:22:15.929918200Z     at new GitError (/home/theia/node_modules/dugite-extra/lib/core/git.js:81:28)
2019-03-21T06:22:15.929923800Z     at Object.<anonymous> (/home/theia/node_modules/dugite-extra/lib/core/git.js:256:27)
2019-03-21T06:22:15.929927700Z     at step (/home/theia/node_modules/dugite-extra/lib/core/git.js:50:23)
2019-03-21T06:22:15.929930800Z     at Object.next (/home/theia/node_modules/dugite-extra/lib/core/git.js:31:53)
2019-03-21T06:22:15.929933800Z     at fulfilled (/home/theia/node_modules/dugite-extra/lib/core/git.js:22:58)
2019-03-21T06:22:15.929936900Z     at <anonymous>
2019-03-21T06:22:15.929939900Z     at process._tickCallback (internal/process/next_tick.js:188:7)

The error is repeated every some seconds.

Second problem: The code completion is not working for my Java sources and the dependent Java classes are not found. The project is a Maven project.
I saw that you fixed the problem with Maven/Gradle for the next release of the Java language version of theia so this problem may disappear.

**Comment by marcdumais-work** [comment]
@UdoW Thanks for opening this issue.

1) git errors: This is related to the image bundling a git version that's too old for `@theia/git`, which needs `v2.11+`. I checked all the images in this repo, that we publish on `dockerhub`, and found another one with the same issue: `theia-go`. I opened a separate [issue, #156, ](https://github.com/theia-ide/theia-apps/issues/156) to deal with both.

2) Missing Maven/Gradle: We have a [PR](https://github.com/theia-ide/theia-apps/pull/148) under review that covers adding these two to `theia-java` and `theia-full`. It has been stalled for a few days, and I plan to submit my own version soon, unless there is progress. 

What I'll do is re-formulate this issue's title to be about the missing Maven/Gradle; we can use #156 to track the git issue part.

**Comment by marcdumais-work** [comment]
@UdoW 
> If I open Theia in the browser I see the empty workspace.

This is normal: the default workspace directory, `/home/project` is empty in the image. One way to use the various Theia images is to mount there a host folder, as a docker volume; then the default workspace would contain what was mounted. e.g.: 
`docker run -it -p 3000:3000 -v "$(pwd):/home/project:cached" theiaide/theia-java:latest`

However be aware that this can lead to permission issues: it's unlikely that your user on the host will have the same identity as the user you'll be using in the image, and that can be a headache to manage.

**Comment by marcdumais-work** [comment]
We already have an issue for adding Maven and Gradle to java and full images: https://github.com/theia-ide/theia-apps/issues/131 . @UdoW please follow this one instead.

Closing this issue here as duplicate.
