### ISSUE TITLE
Permissino denied when trying to save

### ISSUE THREAD

**Issue by sidazhang** [theia-ide/theia-apps#160]
Open the editor like:

`docker run -it -p 3000:3000 -v "$(pwd):/home/project:cached" theiaide/theia:next`

When I click save, I get the following error
```
root ERROR Request setContent failed with error: EACCES: permission denied, open '<path to my file>' Error: EACCES: permission denied, open '<path to my file>'
root ERROR Error: Request 'setContent' failed
    at Proxy.<anonymous> (http://localhost:3000/bundle.js:19:585923)
    at e.<anonymous> (http://localhost:3000/bundle.js:30:131142)
    at http://localhost:3000/bundle.js:30:129031
    at Object.next (http://localhost:3000/bundle.js:30:129136)
    at a (http://localhost:3000/bundle.js:30:127882)
```

**Comment by jwulf** [comment]
I'm getting this on Ubuntu 18.04

**Comment by soerendip** [comment]
Me tool
