### ISSUE TITLE
[yangster-docker] build issue using "next" version

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia-apps#30]
I think this was working last week. Now there is this build error:

``` javascript
ERROR in ./~/theia-yang-extension/lib/frontend/monaco/yang-monaco-editor-provider.js
Module not found: Error: Can't resolve '@theia/monaco/lib/browser/monaco-diff-nagivator-factory' in '/home/theia/node_modules/theia-yang-extension/lib/frontend/monaco'
 @ ./~/theia-yang-extension/lib/frontend/monaco/yang-monaco-editor-provider.js 50:38-104
 @ ./~/theia-yang-extension/lib/frontend/language/frontend-extension.js
 @ ./src-gen/frontend/index.js

Error: webpack failed with the exit code 2
    at ChildProcess.<anonymous> (/home/theia/node_modules/@theia/application-manager/lib/application-process.js:59:28)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
error Command failed with exit code 1.

```

It seems that a typo in this filename ```@theia/monaco/src/browser/monaco-diff-nagivator-factory.ts``` has been fixed in the main Theia repo, and we would need to use the new name: 

"nagivator" => "navigator"

**Comment by marcdumais-work** [comment]
resolved by https://github.com/theia-ide/yangster/pull/57/commits/1efc4d604ea997cbc04385d1738b89e36c715286
