### ISSUE TITLE
Next version of theia applications do not build

### ISSUE THREAD

**Issue by chrbayer** [theia-ide/theia-apps#371]
Since yesterday the next version of the full image does not build any more, I get this error messages (on 82eff419a52242513892e2c947046f53d0197dd6):

```
[4/4] Building fresh packages...
success Saved lockfile.
Done in 114.42s.
yarn run v1.13.0
$ /home/theia/node_modules/.bin/theia build
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '../lib/theia'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/theia/node_modules/@theia/cli/bin/theia:2:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.13.0
$ /home/theia/node_modules/.bin/theia download:plugins
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '../lib/theia'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/theia/node_modules/@theia/cli/bin/theia:2:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn --cache-folder ./ycache && rm -rf ./ycache &&     NODE_OPTIONS="--max_old_space_size=4096" yarn theia build ;    yarn theia download:plugins' returned a non-zero code: 1
```

I already tried to increase max_old_space_size, but that didn't help.

Please see https://github.com/eclipse-theia/theia/issues/7974

**Comment by marcdumais-work** [comment]
Thanks for the bug report @chrbayer . 

I think ATM that all `next` Theia applications seem to have this build problems, so the scope is larger than just the full image. 

See this upstream issue:
https://github.com/eclipse-theia/theia/issues/7974

**Comment by marcdumais-work** [comment]
The issue now seems resolved.

**Comment by chrbayer** [comment]
Works for me too, closing the issue.
