### ISSUE TITLE
unable to debug anymore

### ISSUE THREAD

**Issue by smoebody** [theia-ide/theia-apps#483]
### Bug Description:
I am unable to start a debug session, neither for php nor node - which both used to work some time ago.
Since i build my own docker-image based on https://github.com/theia-ide/theia-apps/tree/master/theia-full-docker i cannot say exactly when it stopped to work, because i build on an irregular basis.

### Steps to Reproduce:

1. Open project with debug-configuration
2. Klick the "Start Debugging" Button
3. Observe the error message

### Additional Information

- Operating System: https://github.com/theia-ide/theia-apps/tree/master/theia-full-docker 
- Theia Version: latest (built yesterday, 14.Jul.)

Logs:
```
root ERROR Error starting the debug session TypeError: is_electron_1.default is not a function
    at Object.startDebugAdapter (/app/node_modules/@theia/plugin-ext/lib/plugin/node/debug/plugin-debug-adapter-starter.js:44:48)
    at DebugExtImpl.<anonymous> (/app/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:725:82)
    at step (/app/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:33:23)
    at Object.next (/app/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:14:53)
    at fulfilled (/app/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by vince-fugnitto** [comment]
@smoebody thank you for reporting the issue, I believe it is related to the upstream issue https://github.com/eclipse-theia/theia/issues/9729.
It should be fixed as part of the `next` tag: https://github.com/eclipse-theia/theia/pull/9730.

**Comment by smoebody** [comment]
@vince-fugnitto Thanks for the hint. switching to the next-tag solved the problem

**Comment by marcdumais-work** [comment]
There was a theia release today, so this should be fixed with `latest` too now.

**Comment by smoebody** [comment]
I can confirm, that the problem is solved.
