### ISSUE TITLE
Container bulld error - Couldn't find any versions for "@theia/core" that matches "1.28.0-next.0+f35df816abc"

### ISSUE THREAD

**Issue by filipthoen2** [theia-ide/theia-apps#517]
Hello there!

I tried to rebuild the theia-docker & theia-cpp-docker container images on Ubuntu 18.04 & Docker v20.10.17, and in both cases I get the error:

>> docker build --no-cache --build-arg version=next   -t theia:next . 

```
Error: Couldn't find any versions for "@theia/core" that matches "1.28.0-next.0+f35df816abc"
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.4/lib/cli.js:721:66)
    at new MessageError (/opt/yarn-v1.22.4/lib/cli.js:750:123)
    at Function.<anonymous> (/opt/yarn-v1.22.4/lib/cli.js:50545:13)
    at Generator.next (<anonymous>)
    at step (/opt/yarn-v1.22.4/lib/cli.js:310:30)
    at /opt/yarn-v1.22.4/lib/cli.js:321:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I can't even tell where the version "1.28.0-next.0+f35df816abc" error originates from.

Any tips or are these Dockerfile's no longer maintained, in favor of Theia Blueprint?

Thanks,

Filip

<details>
<summary>Full Build Log</summary>

<br />

```
sudo docker build --no-cache --build-arg version=next   -t theia:next . 
Sending build context to Docker daemon  26.62kB
Step 1/20 : ARG NODE_VERSION=12.18.3
Step 2/20 : FROM node:${NODE_VERSION}-alpine
12.18.3-alpine: Pulling from library/node
cbdbe7a5bc2a: Pull complete 
091983d60f65: Pull complete 
7bacc183740f: Pull complete 
c4a5a5d270d4: Pull complete 
Digest: sha256:c8efbb31ceea05eb063ce1e598593237c73735ee0055190b8d8c48f0176b5721
Status: Downloaded newer image for node:12.18.3-alpine
 ---> 18f4bc975732
Step 3/20 : RUN apk add --no-cache make pkgconfig gcc g++ python libx11-dev libxkbfile-dev libsecret-dev
 ---> Running in f4bfd84fdf53
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/73) Upgrading musl (1.1.24-r2 -> 1.1.24-r3)
(2/73) Upgrading libstdc++ (9.2.0-r4 -> 9.3.0-r0)
(3/73) Installing binutils (2.33.1-r1)
(4/73) Installing gmp (6.1.2-r1)
(5/73) Installing isl (0.18-r0)
(6/73) Installing libgomp (9.3.0-r0)
(7/73) Installing libatomic (9.3.0-r0)
(8/73) Installing mpfr4 (4.0.2-r1)
(9/73) Installing mpc1 (1.1.0-r1)
(10/73) Installing gcc (9.3.0-r0)
(11/73) Installing musl-dev (1.1.24-r3)
(12/73) Installing libc-dev (0.7.2-r0)
(13/73) Installing g++ (9.3.0-r0)
(14/73) Installing libgpg-error (1.36-r2)
(15/73) Installing libgcrypt (1.8.8-r1)
(16/73) Installing libffi (3.2.1-r6)
(17/73) Installing libintl (0.20.1-r2)
(18/73) Installing libblkid (2.34-r1)
(19/73) Installing libmount (2.34-r1)
(20/73) Installing pcre (8.43-r1)
(21/73) Installing glib (2.62.6-r0)
(22/73) Installing libsecret (0.19.1-r0)
(23/73) Installing libbz2 (1.0.8-r1)
(24/73) Installing expat (2.2.9-r1)
(25/73) Installing gdbm (1.13-r1)
(26/73) Installing xz-libs (5.2.4-r0)
(27/73) Installing ncurses-terminfo-base (6.1_p20200118-r4)
(28/73) Installing ncurses-libs (6.1_p20200118-r4)
(29/73) Installing readline (8.0.1-r0)
(30/73) Installing sqlite-libs (3.30.1-r2)
(31/73) Installing python3 (3.8.10-r0)
(32/73) Installing gettext-asprintf (0.20.1-r2)
(33/73) Installing libunistring (0.9.10-r0)
(34/73) Installing gettext-libs (0.20.1-r2)
(35/73) Installing libxml2 (2.9.12-r0)
(36/73) Installing gettext (0.20.1-r2)
(37/73) Installing gettext-dev (0.20.1-r2)
(38/73) Installing bzip2-dev (1.0.8-r1)
(39/73) Installing libxml2-utils (2.9.12-r0)
(40/73) Installing libxslt (1.1.34-r0)
(41/73) Installing docbook-xml (4.5-r6)
Executing docbook-xml-4.5-r6.post-install
(42/73) Installing docbook-xsl (1.79.2-r2)
Executing docbook-xsl-1.79.2-r2.post-install
(43/73) Installing linux-headers (4.19.36-r0)
(44/73) Installing pkgconf (1.6.3-r0)
(45/73) Installing libffi-dev (3.2.1-r6)
(46/73) Installing libpcre16 (8.43-r1)
(47/73) Installing libpcre32 (8.43-r1)
(48/73) Installing libpcrecpp (8.43-r1)
(49/73) Installing pcre-dev (8.43-r1)
(50/73) Installing libuuid (2.34-r1)
(51/73) Installing libfdisk (2.34-r1)
(52/73) Installing libsmartcols (2.34-r1)
(53/73) Installing util-linux-dev (2.34-r1)
(54/73) Installing zlib-dev (1.2.11-r3)
(55/73) Installing glib-dev (2.62.6-r0)
(56/73) Installing libsecret-dev (0.19.1-r0)
(57/73) Installing libxau (1.0.9-r0)
(58/73) Installing xorgproto (2019.2-r0)
(59/73) Installing libxau-dev (1.0.9-r0)
(60/73) Installing xcb-proto (1.13-r4)
(61/73) Installing libbsd (0.10.0-r0)
(62/73) Installing libxdmcp (1.1.3-r0)
(63/73) Installing libxcb (1.13.1-r0)
(64/73) Installing libpthread-stubs (0.3-r5)
(65/73) Installing libxdmcp-dev (1.1.3-r0)
(66/73) Installing libxcb-dev (1.13.1-r0)
(67/73) Installing xtrans (1.4.0-r1)
(68/73) Installing libx11 (1.6.12-r1)
(69/73) Installing libx11-dev (1.6.12-r1)
(70/73) Installing libxkbfile (1.1.0-r0)
(71/73) Installing libxkbfile-dev (1.1.0-r0)
(72/73) Installing make (4.2.1-r2)
(73/73) Installing python2 (2.7.18-r0)
Executing busybox-1.31.1-r9.trigger
Executing glib-2.62.6-r0.trigger
No schema files found: doing nothing.
OK: 330 MiB in 87 packages
Removing intermediate container f4bfd84fdf53
 ---> e0845c055246
Step 4/20 : ARG version=latest
 ---> Running in 12f63060a197
Removing intermediate container 12f63060a197
 ---> 915b666272ca
Step 5/20 : WORKDIR /home/theia
 ---> Running in 99cb0eb1fa5f
Removing intermediate container 99cb0eb1fa5f
 ---> bfd0c8753f83
Step 6/20 : ADD $version.package.json ./package.json
 ---> 0285999d71ca
Step 7/20 : ARG GITHUB_TOKEN
 ---> Running in 84da918f687b
Removing intermediate container 84da918f687b
 ---> 12d99eb4aac0
Step 8/20 : RUN yarn --pure-lockfile &&     NODE_OPTIONS="--max_old_space_size=4096" yarn theia build &&     yarn theia download:plugins &&     yarn --production &&     yarn autoclean --init &&     echo *.ts >> .yarnclean &&     echo *.ts.map >> .yarnclean &&     echo *.spec.* >> .yarnclean &&     yarn autoclean --force &&     yarn cache clean
 ---> Running in ef2ea40aa2b7
yarn install v1.22.4
info No lockfile found.
$ node-gyp install
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.18.3 | linux | x64
gyp http GET https://unofficial-builds.nodejs.org/download/release/v12.18.3/node-v12.18.3-headers.tar.gz
gyp http 200 https://unofficial-builds.nodejs.org/download/release/v12.18.3/node-v12.18.3-headers.tar.gz
gyp http GET https://unofficial-builds.nodejs.org/download/release/v12.18.3/SHASUMS256.txt
12.18.3
gyp http 200 https://unofficial-builds.nodejs.org/download/release/v12.18.3/SHASUMS256.txt
gyp info ok 
[1/4] Resolving packages...
error Couldn't find any versions for "@theia/core" that matches "1.28.0-next.0+f35df816abc"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find any versions for "@theia/core" that matches "1.28.0-next.0+f35df816abc"
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.4/lib/cli.js:721:66)
    at new MessageError (/opt/yarn-v1.22.4/lib/cli.js:750:123)
    at Function.<anonymous> (/opt/yarn-v1.22.4/lib/cli.js:50545:13)
    at Generator.next (<anonymous>)
    at step (/opt/yarn-v1.22.4/lib/cli.js:310:30)
    at /opt/yarn-v1.22.4/lib/cli.js:321:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find any versions for "@theia/core" that matches "1.28.0-next.0+f35df816abc"
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.4/lib/cli.js:721:66)
    at new MessageError (/opt/yarn-v1.22.4/lib/cli.js:750:123)
    at Function.<anonymous> (/opt/yarn-v1.22.4/lib/cli.js:50545:13)
    at Generator.next (<anonymous>)
    at step (/opt/yarn-v1.22.4/lib/cli.js:310:30)
    at /opt/yarn-v1.22.4/lib/cli.js:321:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
The command '/bin/sh -c yarn --pure-lockfile &&     NODE_OPTIONS="--max_old_space_size=4096" yarn theia build &&     yarn theia download:plugins &&     yarn --production &&     yarn autoclean --init &&     echo *.ts >> .yarnclean &&     echo *.ts.map >> .yarnclean &&     echo *.spec.* >> .yarnclean &&     yarn autoclean --force &&     yarn cache clean' returned a non-zero code: 1
```

</details>

**Comment by vince-fugnitto** [comment]
@filipthoen2 thank you for the discussion, as you pointed out the dockerfiles are no longer maintained (https://github.com/theia-ide/theia-apps/issues/496).

If you are to maintain your own dockerfile I'd suggest going for `latest` releases and not `next` (which can sometimes cause version mismatches). In essence you'll want to make sure that each `@theia` dependency is the same version.)
