### ISSUE TITLE
Theia-full image doesn't work

### ISSUE THREAD

**Issue by haixinxu** [theia-ide/theia-apps#86]
log from stdout
`

yarn run v1.9.4
warning Skipping preferred cache folder "/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1066760000".
$ /home/theia/node_modules/.bin/theia start /home/project --hostname=0.0.0.0
Starting server worker...
Server worker has been started. [ID: 1 \| PID: 38]
Failed to start the backend application.
{ Error: Cannot find module '@theia/debug/lib/node/debug-model'
at Function.Module._resolveFilename (module.js:548:15)
at Function.Module._load (module.js:475:25)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/home/theia/node_modules/@theia/cpp/lib/node/cpp-backend-module.js:20:21)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3) code: 'MODULE_NOT_FOUND' }
/home/theia/node_modules/@theia/core/lib/node/cluster/main.js:58
throw reason;
^

Error: Cannot find module '@theia/debug/lib/node/debug-model'
at Function.Module._resolveFilename (module.js:548:15)
at Function.Module._load (module.js:475:25)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/home/theia/node_modules/@theia/cpp/lib/node/cpp-backend-module.js:20:21)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
Server worker has been disconnected. [ID: 1 \| PID: 38]
Server worker failed to start within 5000 milliseconds.
Pass a greater value as '--startup-timeout' option to increase the timeout or a negative to disable.
Done in 1.24s.

`

**Comment by marcdumais-work** [comment]
@haixinxu Thanks for the report. Somehow this built in our CI, so this issue might be intermittent. 

@marechal-p : Might we have forgotten to add a dependency for ```@theia/debug``` in ```@theia/cpp```? 

```
Error: Cannot find module '@theia/debug/lib/node/debug-model'
[...]
at Object. (/home/theia/node_modules/@theia/cpp/lib/node/cpp-backend-module.js:20:21)
[...]
```

**Comment by marcdumais-work** [comment]
@haixinxu you should be good with the ```next``` version of this image. For now we rolled back the commit that introduced the dependency, and will bring it back in a way that will not.
