### ISSUE TITLE
Possible missing file in full image

### ISSUE THREAD

**Issue by haixinxu** [theia-ide/theia-apps#87]
log:
> yarn run v1.9.4
   warning Skipping preferred cache folder "/.cache/yarn" because it is not writable.
   warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1066760000".
   $ /home/theia/node_modules/.bin/theia start /home/project --hostname=0.0.0.0
   Starting server worker...
   Server worker has been started. [ID: 1 \ PID: 38]
   Error: @postConstruct error in class TypeScriptContribution: EACCES: permission denied, open '/home/theia/.application-module-loader.js'
   at _postConstruct (/home/theia/node_modules/inversify/lib/resolution/instantiation.js:30:19)
   at Object.resolveInstance (/home/theia/node_modules/inversify/lib/resolution/instantiation.js:47:5)
   at /home/theia/node_modules/inversify/lib/resolution/resolver.js:72:42
   at /home/theia/node_modules/inversify/lib/resolution/resolver.js:34:24
   at Array.map (<anonymous>)
   at /home/theia/node_modules/inversify/lib/resolution/resolver.js:32:34
   at Object.resolve (/home/theia/node_modules/inversify/lib/resolution/resolver.js:96:12)
   at /home/theia/node_modules/inversify/lib/container/container.js:320:37
   at Container._get (/home/theia/node_modules/inversify/lib/container/container.js:311:44)
   at Container.getAll (/home/theia/node_modules/inversify/lib/container/container.js:239:21)
   { Error: EACCES: permission denied, open '/home/theia/package-backup.json'
   at Object.fs.openSync (fs.js:646:18)
   at copyFileSync (/home/theia/node_modules/fs-extra/lib/copy-sync/copy-file-sync.js:23:18)
   at Object.copySync (/home/theia/node_modules/fs-extra/lib/copy-sync/copy-sync.js:43:5)
   at ApplicationProject.backup (/home/theia/node_modules/@theia/extension-manager/lib/node/application-project.js:325:16)
   at new ApplicationProject (/home/theia/node_modules/@theia/extension-manager/lib/node/application-project.js:114:14)
   at _createInstance (/home/theia/node_modules/inversify/lib/resolution/instantiation.js:21:12)
   at Object.resolveInstance (/home/theia/node_modules/inversify/lib/resolution/instantiation.js:41:18)
   at /home/theia/node_modules/inversify/lib/resolution/resolver.js:72:42
   at Array.map (<anonymous>)
   at Object.resolveInstance (/home/theia/node_modules/inversify/lib/resolution/instantiation.js:40:67)
   errno: -13,
   code: 'EACCES',
   syscall: 'open',
   path: '/home/theia/package-backup.json' }
   Server worker is ready to accept messages. [ID: 1 \ PID: 38]
   root ERROR Could not start contribution Error: EACCES: permission denied, open '/home/theia/.application-module-loader.js'
   at Object.fs.openSync (fs.js:646:18)
   at Object.fs.writeFileSync (fs.js:1299:33)
   at ApplicationPackage.get [as resolveModule] (/home/theia/node_modules/@theia/application-package/lib/application-package.js:379:20)
   at ApplicationPackage.get [as extensionPackages] (/home/theia/node_modules/@theia/application-package/lib/application-package.js:158:157)
   at ExtensionMetricsContribution.startCollecting (/home/theia/node_modules/@theia/metrics/lib/node/extensions-metrics-contribution.js:40:59)
   at /home/theia/node_modules/@theia/metrics/lib/node/metrics-backend-application-contribution.js:46:26
   at Array.forEach (<anonymous>)
   at MetricsBackendApplicationContribution.onStart (/home/theia/node_modules/@theia/metrics/lib/node/metrics-backend-application-contribution.js:45:50)
   at BackendApplication.<anonymous> (/home/theia/node_modules/@theia/core/lib/node/backend-application.js:283:54)
   at step (/home/theia/node_modules/@theia/core/lib/node/backend-application.js:59:23)
   root INFO Theia app listening on http://0.0.0.0:3000 .
   Received message which is neither a response nor a notification message:
   "3000"
   root ERROR Cannot find a service for the path: /services/logger
   root ERROR Cannot find a service for the path: /services/messageService
   root ERROR Cannot find a service for the path: /services/filesystem
   root ERROR Cannot find a service for the path: /services/fs-watcher
   root ERROR Cannot find a service for the path: /services/workspace
   root ERROR Cannot find a service for the path: /services/envs
   root ERROR Cannot find a service for the path: /services/git
   root ERROR Cannot find a service for the path: /services/git-watcher
   root ERROR Cannot find a service for the path: /services/mini-browser-service
   root ERROR Cannot find a service for the path: /services/task
   root ERROR Cannot find a service for the path: /services/fs-watcher
   root ERROR Cannot find a service for the path: /services/application
   root ERROR Cannot find a service for the path: /services/extensions
   root ERROR Cannot find a service for the path: /services/search

**Comment by marcdumais-work** [comment]
Looks like maybe a file permission issue. Will try to reproduce

**Comment by marcdumais-work** [comment]
I was not able to reproduce this error. ```theiaide/theia-full:latest``` fails at startup with a different error: the missing dependency to ```@theia/debug```. PR for that other one: https://github.com/theia-ide/theia-apps/pull/88

**Comment by haixinxu** [comment]
it is the next version of the image

**Comment by marcdumais-work** [comment]
@haixinxu so you're using our image from dockerhub (```next``` version from this page? 
https://hub.docker.com/r/theiaide/theia-full/tags/)? I was not able to reproduce the issue this way. And BTW, the code introduced in the PR above is not present any more, in "next". 

Maybe you need to pull a fresh copy? e.g. 
```docker pull theiaide/theia-full:next```

**Comment by haixinxu** [comment]
the issue is still present on kubernetes platforms eg. openshift, maybe it is a permission issue.

**Comment by marcdumais-work** [comment]
> the issue is still present on kubernetes platforms eg. openshift, maybe it is a permission issue.

@haixinxu That is not officially supported by this image, at least not at this time. We have no access to openshift that would permit testing that we are or remain compatible. If you or someone else is willing to contribute and maintain a version of the full image that runs on e.g. openshift, we can host it in this repo. 

FYI, we already have a base image that's supposed to work on openshift, that could be used as inspiration: 
https://github.com/theia-ide/theia-apps/tree/master/theia-openshift-docker

**Comment by marcdumais-work** [comment]
@JamesDrummond FYI.

**Comment by devcomb** [comment]
@haixinxu Fill free to use my openshift variant. It's under a lot of constant changes right now so be warned. Just deploy the image 'docker.io/devcomb/theia-openshift:latest' and create a route to port 3000. You can follow my old article at https://medium.com/@james_devcomb/theia-on-openshift-f4ee8832a587 .

 If you want to look at a use case which I am actively improving look at my article at https://medium.com/@james_devcomb/developing-a-nodejs-application-with-theia-in-openshift-a07c00975da2 . It uses a deployment configuration to fully develop Node.js microservices with Theia. If you want to quickly try it out just run the following CLI which is also in my article but I will put it here for quick access.

```
oc login -u <your username>
oc new-project theia-example
oc create -n theia-example -f https://raw.githubusercontent.com/devcomb/nodejs-ex/master/openshift/templates/nodejs-theia.yaml
oc new-app nodejs-theia
```

**Comment by devcomb** [comment]
Currently my docker image and articles are based on the following repository. Because I am actively developing I am not ready to create official pull request to this/theia-ide repository.

https://github.com/devcomb/theia-apps/tree/master/theia-openshift-docker
